spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventsys_lb?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 23422215
    hikari:
      maximum-pool-size: 10         # Número maximo de conexiones en el pool
      minimum-idle: 5               # Mínimo de conexiones inactivas
      idle-timeout: 600000          # Tiempo (ms) antes de cerrar una conexión inactiva
      max-lifetime: 1800000         # Tiempo maximo de vida (ms) de una conexión
      connection-timeout: 30000     # Tiempo de espera para obtener una conexión
      jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true

    security:
      jwt:
        secret: QulywYuiMZzR90QVVIuIZs9UmBAbDkQQvBmYHlRJtfmJPcfZoa7Hkzv-P9Tvy10f5NvAASEt1NAyS4ZGoWHAEw
        access-token-expiration: 900000  # 15 minutos en milisegundos
        refresh-token-expiration: 900000  # 15 minutos en milisegundos

    logging:
      level:
        root: INFO
        org.hibernate.orm.jdbc.bind: TRACE         # Muestrá los valores que se envían a los parámetros?
        org.hibernate.orm.jdbc.extract: TRACE    # Muestra los valores que se extraen desde la BD
        org.hibernate.type.descriptor.sql: TRACE   # Para ver más detalles de tipos